### ISSUE TITLE
Doesn't build on windows

### ISSUE THREAD

**Issue by ffranco-daitan** [tugrul/node-mcrypt#11]
Trying to install this extension on windows fails with this error:

..\src\mcrypt.cc(7): fatal error C1083: Cannot open include file: 'mcrypt.h': No such file or directory [**********\node_modules\mcrypt\build\mcrypt.vcxproj]

Any ideas on how to fix that?

**Comment by theHazzard** [comment]
I've managed to load mcrypt.h but now I'm having this errors


"d:\desarrollo\apinodesocket-barcode\node_modules\mcrypt\build\binding.sln" (default target)  (1) ->
"d:\desarrollo\apinodesocket-barcode\node_modules\mcrypt\build\mcrypt.vcxproj" (default targ et) (2) ->
(ClCompile target) ->
  ..\src\mcrypt.cc(43): error C2057: expected constant expression [d:\desarrollo\apinodesock et-barcode\node_modules\mcrypt\build\mcrypt.vcxproj]
  ..\src\mcrypt.cc(43): error C2466: cannot allocate an array of constant size 0 [d:\desarro llo\apinodesocket-barcode\node_modules\mcrypt\build\mcrypt.vcxproj]
  ..\src\mcrypt.cc(43): error C2133: 'keyBuf' : unknown size [d:\desarrollo\apinodesocket-ba rcode\node_modules\mcrypt\build\mcrypt.vcxproj]
  ..\src\mcrypt.cc(46): error C2057: expected constant expression [d:\desarrollo\apinodesock et-barcode\node_modules\mcrypt\build\mcrypt.vcxproj]
  ..\src\mcrypt.cc(46): error C2466: cannot allocate an array of constant size 0 [d:\desarro llo\apinodesocket-barcode\node_modules\mcrypt\build\mcrypt.vcxproj]
  ..\src\mcrypt.cc(46): error C2133: 'ivBuf' : unknown size [d:\desarrollo\apinodesocket-bar code\node_modules\mcrypt\build\mcrypt.vcxproj]

**Comment by benag** [comment]
did someone solved this?

**Comment by gdlm91** [comment]
@theHazzard How did you do to load the mcrypt.h??

**Comment by Cauldrath** [comment]
I was able to get this to at least install on Windows.  Make sure for both libraries you change the "runtime library" setting under "code generation" to "MT" so you don't get conflicts down the line and compile for release.  You'll get errors that look like this if you don't:
```MSVCRT.lib(MSVCR100.dll) : error LNK2005: _free already defined in LIBCMT.lib(free.obj)```

First you need to generate dirent: (I wasn't able to compile this with VC express 2010, but was with 2012)
https://github.com/winlibs/dirent
Take the dirent_a.lib file you generate and add it to the /lib directory in this project:
https://github.com/winlibs/libmcrypt
Copy the libmcrypt_a.lib file generated to the root of your node-mcrypt directory.
Add the .h files from the include directory to your node-mcrypt directory.  (I made a new directory named "libmcrypt".)
Open the binding.gyp file.
Add the new include directory to the "include_dirs" list (For mine, it was adding the line ``"./libmcrypt",``)
Adjust the library being linked to go to your local version.  (The line that is ``"-lmcrypt",`` is changed to ``"-l../libmcrypt_a",``
Then, to fix the issue theHazzard ran into, go to here:
https://github.com/tugrul/node-mcrypt/blob/24da58b7b8b7cc6d5a11a742da159b49ace2154c/src/mcrypt.cc#L43

Change the remainder of the function to:
```
    char *keyBuf = new char[key.length()];
    key.copy(keyBuf, key.length());
    
    char *ivBuf = new char[iv.length()];
    iv.copy(ivBuf, iv.length());

    if ((*result = mcrypt_generic_init(mcrypt_, keyBuf, key.length(), ivBuf)) < 0) {
        delete keyBuf;
        delete ivBuf;
        return targetData;
    }

    if ((*result = modify(mcrypt_, targetData, *length)) != 0) {
        delete keyBuf;
        delete ivBuf;
        return targetData;
    }

    *result = mcrypt_generic_deinit(mcrypt_);

    delete keyBuf;
    delete ivBuf;
    return targetData;
```

The problem is that gcc will allow you to specify variable length arrays with static allocations, but Visual Studio does not, so this change makes it dynamic.  There's probably cleaner ways to make all these steps work, but I mostly was just concerned about it running at all.

**Comment by Cauldrath** [comment]
Alternatively, I made a fork with my unlicensed hacks that I in no way endorse for production code:
https://github.com/Cauldrath/node-mcrypt/tree/windows

**Comment by tugrul** [comment]
@Cauldrath is there a way to seperate libmcrypt dependency from addon? There are some release on original source ftp://mcrypt.hellug.gr/pub/crypto/mcrypt/libmcrypt/win32/ also these contain static build file and headers. 

So I'm going to lookup changes from your fork

**Comment by Cauldrath** [comment]
The libraries in there are dlls and .a files that seem to be for use with cygwin.  There's probably a way to get them to work, but I'm not that familiar with node-gyp.

Also, apparently you can just name the libmcrypt_a.lib file mcrypt.lib and throw it in the Visual Studio VC lib folder and the mcrypt.h and mutils folders in your Visual Studio VC include folder and it will work fine with no changes to the binding.gyp file.  It seems like you could just include installation instructions and the change to make those variable length array allocations dynamic and call it Windows-compatible.

**Comment by tugrul** [comment]
@Cauldrath Yeah node-gyp not supports mingw/cygwin. Good idea to patching Visual Studio folder. Can you share a project that automate this thing (to build and install libmcrypt to Visual Studio VC folder) I'm going to reference your project as dependency to use on Windows. 

Publishing lib file is able to feel insecure instead of project source for other users. 

Thanks

**Comment by Cauldrath** [comment]
Sorry, installers are a bit outside my area of expertise.

**Comment by tugrul** [comment]
@Cauldrath there is no requirement for installers. Only automation is enough like Makefile. A .bat file could be done instead of Makefile. build.bat install.bat etc..

**Comment by tugrul** [comment]
I'm able to static build using gyp dependency. I'm going to make changes to build Windows and going to need no more external library installation for all platforms.

**Comment by tugrul** [comment]
I published 0.1.1 version to NPM. This version is dependency free and able to use on Windows.

**Comment by ffranco-daitan** [comment]
@tugrul Unfortunately it's still not building. Although I've followed all instructions in the node-gyp README, my build fails with this message:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(152,5): error : Required file "" is missing. [D:\web\guaycuru\node-mcrypt\build\mcrypt.vcxproj]
```

Has anyone been able to build it on Windows? I'm using Windows 7 x64.

**Comment by InstanceOfMichael** [comment]
I am having this issue with v0.0.15 and a non-windows system.

```
$ uname -a
Linux client1test 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tugrul** [comment]
@ffranco-daitan i published `mcrypt@0.1.8` and i'm able to install on windows
